version: '3'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - .env
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
