version: '3.9'
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    networks:
      - privacy_net

  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - privacy_net

  mongodb:
    image: mongo:6
    volumes:
      - data:/data/db
    networks:
      - privacy_net

networks:
  privacy_net:
    internal: true

volumes:
  data:
