version: '3.9'
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - '5000:5000'
    networks:
      - internal
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    networks:
      - internal
  mongodb:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    networks:
      - internal

volumes:
  mongo-data:

networks:
  internal:
    internal: true
